Added differential steering
automat-ed/simulation pull request #18
Opened 2021-02-18 16:13 UTC by SmejoTT

Solves #17

2021-02-18 18:21 UTC, Siliconlad requested changes
Your `keyboardInput()` method could probably be its own ROS node in autonomous? It can listen to keyboard input and just publish `geometry_msgs/Twist` messages. That way we don't need different controllers.

2021-02-18 18:21 UTC, Siliconlad commented on lib/steering/src/diffSteering.cpp
> +  webots::Keyborad keyboard;
```suggestion
  webots::Keyboard keyboard;
```

2021-02-18 18:21 UTC, Siliconlad commented on lib/steering/src/diffSteering.cpp
> +}
```suggestion
}

```

2021-02-18 18:21 UTC, Siliconlad commented on src/full_controller.cpp
> +  webots::Motor *front_left_wheel = robot->getMotor("front_left_wheel");
Can you not combine this into:
```cpp
webots::Motor *motors[4] = {
    robot->getMotor("front_left_wheel"),
    robot->getMotor("front_right_wheel"),
    robot->getMotor("rear_left_wheel"),
    robot->getMotor("front_right_wheel")
};
```
Or if you don't like that:
```cpp
webots::Motor *motors[4];
motors[0] = robot->getMotor("front_left_wheel");
motors[1] = robot->getMotor("front_right_wheel");
motors[2] = robot->getMotor("rear_left_wheel");
motors[3] = robot->getMotor("front_right_wheel");
};
```

2021-02-18 18:21 UTC, Siliconlad commented on lib/steering/include/diffSteering.hpp
> +  void keyboardInput();
You'll need to move this method (`keyboardInput`) into the public section of this class declaration if you want to call it from outside the class like you do in `full_controller_keyboard`.

2021-02-18 18:21 UTC, Siliconlad commented on src/full_controller_keyboard.cpp
> +  webots::Motor *front_left_wheel = robot->getMotor("front_left_wheel");
See above for making these more concise.

2021-02-20 17:59 UTC, Siliconlad requested changes
Two other things:
1. I thought we were going to create a separate node for keyboard control? That way we can remove the `keyboardInput` method.
2. Is it possible to include wheel odometry as part of the steering? Or maybe as a separate file inside the steering library? That would be useful for localization.

2021-02-20 17:59 UTC, Siliconlad commented on CMakeLists.txt
> +target_link_libraries(full_controller steering ${WEBOTS_LIB} ${catkin_LIBRARIES})
```suggestion
target_link_libraries(full_controller sensors steering ${WEBOTS_LIB} ${catkin_LIBRARIES})
```

2021-02-20 17:59 UTC, Siliconlad commented on CMakeLists.txt
>  ## Declare a C++ library
```suggestion
## Declare C++ libraries
```

2021-02-20 17:59 UTC, Siliconlad commented on lib/steering/include/steering/diffSteering.hpp
> +  webots::Motor **wheels;
Any reason why we use `webots::Motor**` here but `webots::Motor* motors[]` in the constructor?

2021-02-20 17:59 UTC, Siliconlad commented on lib/steering/src/diffSteering.cpp
> +  std::cout << vel_left;
Use `ROS_INFO` or `ROS_DEBUG` instead. See [ROS Logging](https://wiki.ros.org/roscpp/Overview/Logging).

2021-02-20 17:59 UTC, Siliconlad commented on lib/steering/src/diffSteering.cpp
> +  for (int i = 0; i < 4; i++) {
Can you not check for the length of the array in the `for` loop.

2021-02-20 17:59 UTC, Siliconlad commented on lib/steering/src/diffSteering.cpp
> +  for (int i = 0; i < 4; i++) {
Same here

2021-02-20 22:47 UTC, Siliconlad requested changes
After these minor changes, I think I'm happy to merge.

2021-02-20 22:47 UTC, Siliconlad commented on CMakeLists.txt
>  install(DIRECTORY lib/sensors/include/sensors/
Actually, I think I got this wrong previously. I think it should instead be:
```suggestion
install(DIRECTORY lib/sensors/include
```

2021-02-20 22:47 UTC, Siliconlad commented on CMakeLists.txt
> +install(DIRECTORY lib/steering/include/steering/
Similarly for here:
```suggestion
install(DIRECTORY lib/steering/include
```

2021-02-20 22:47 UTC, Siliconlad commented on lib/steering/src/diffSteering.cpp
> +#include "webots/Keyboard.hpp"
Remove?

2021-02-20 22:47 UTC, Siliconlad commented on lib/steering/src/diffSteering.cpp
> +void DiffSteering::turnOnMotors() {
Do we need this method? Can we not just put it in the constructor where it gets called?

2021-02-20 22:47 UTC, Siliconlad commented on lib/steering/src/diffSteering.cpp
> +void DiffSteering::shutDownMotors() {
Would `stopMotors` be a better name?

2021-02-20 22:47 UTC, Siliconlad commented on worlds/world.wbt
> -      name "gps"
You removed this name?

2021-02-20 23:56 UTC, SmejoTT commented on worlds/world.wbt
> -      name "gps"
It's missing in the main as well.

2021-02-20 23:59 UTC, Siliconlad commented on worlds/world.wbt
> -      name "gps"
Oh ok. I think it would be best to add it just to be explicit even if "gps" is the default.

2021-02-21 10:16 UTC, Siliconlad approved these changes
Looks good!

2021-02-21 10:17 UTC, merged